### ISSUE TITLE
Refactor codebase

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackage-registry-js#2]
# Description

We've recently made changes to https://github.com/okfn/datapackage-registry-py and also https://github.com/dataprotocols/schemas and we need to move this lib forward in sync. 

Additionally, the tests here are not covering the right things (for example, use of the lib is now failing with the recent `$ref` changes on our schemas, even though tests pass).

We want 100% feature consistency with the Python lib, and more or less API consistency (I prefer more, but as long as it does not affect the design of this as a _Javascript_ lib).

Lastly, we are starting to standardise at OKI around ES6 and modern build tools. This is a small lib, so we should update this to ES6 now.
# Tasks
- [x] Add documentation
- [x] Live registry is at http://schemas.datapackages.org/registry.csv
- [x] Remove any remaining use of `es6-promise` as we use `bluebird` as our `Promise` implementation
- [x] Port functionality of the Python registry lib over here. This was done originally, but there is now some catch up to do with the recent changes in the Python lib
- [x] Port to ES6 - this is a somewhat arbitrary requirements, but I'm enforcing us to write ES6 for all new JS as a step towards standardising our whole JS toolchain. Please see https://github.com/okfn/spend-publishing-dashboard and https://github.com/openspending/fiscal-data-js for recent examples of our code in ES6, and https://github.com/openspending/fiscal-data-js/blob/feature/refactor/.jscsrc for the style guide I'm trying to move towards
- [x] Export a browser distribution to the `dist/` directory (Example: https://github.com/openspending/fiscal-data-js/blob/master/webpack.config.js#L5)
- [x] Nice test coverage
- [ ] Publish new version to `npm`

**Comment by vitorbaptista** [comment]
Random thoughts about the local cache, mostly for documentation purposes.

This library should work both on NodeJS and on the browser, so we can't rely on the local filesystem. I've added a commit (https://github.com/okfn/datapackage-registry-js/commit/d4073c12fb9e11e47e44ed1d7c098e9b0fedb599) that embeded the registry and its schemas into the JS file itself when building the browser version (using browserify and https://github.com/Jam3/brfs-babel).

That's working, but there're a few caveats:
- brfs-babel evaluates our JS statically, so we have to maintain a static list of schemas and update them when we update the registry cache (we could automate this, but haven't done it yet);
- We'll have problems with the `$ref` to `definitions.json` that I'm not sure how to solve yet.
- By default, every schema is in the JS file, so it gets bigger.

The advantage is that the same code works both for NodeJS and the browser, and the cache is in the file itself, so there's no need for extra requests.

Thinking better now, I don't think that's a good approach. I think that we should follow the pattern from `datapackage-registry-py` when running on NodeJS (i.e. simply have a default path pointing to the local `registry.csv`), and use `http://schemas.datapackages.org/registry.csv` when on the browser (i.e. not have a cache). This unfortunately will make the code work slightly different depending on where it's run, but overall I think it's simpler than the alternative.

**Comment by pwalsh** [comment]
@vitorbaptista didn't think on all points but @borysyuk dealt with the `$ref` issue in another codebase: https://github.com/okfn/datapackagist

**Comment by pwalsh** [comment]
@vitorbaptista oh yeah: no cache in browser, yes. Sometimes things aren't clear until we write the code :).
